---
- name: Task Delegation
  hosts: linuxservers
  become: true

  tasks:
    - name: Debug Facts Hostname
      ansible.builtin.debug:
        msg: "{{ ansible_facts['nodename'] }}"

    - name: Write File
      ansible.builtin.blockinfile:
        path: ~/file2.txt
        block: "{{ ansible_facts['nodename'] }}"
        create: true
        mode: 0600
      delegate_to: localhost
