---
- name: Task Delegation
  hosts: linuxservers
  become: true

  tasks:
    - name: Debug Facts Hostname
      ansible.builtin.debug:
        msg: "{{ ansible_facts['nodename'] }}"

    - name: Write File
      ansible.builtin.shell:
        shell: "{{ ansible_facts['nodename'] }}"
      delegate_to: localhost
